use crate::common::print_formatted_error::print_formatted_error;

pub struct Vendors {
    pub prettified_vendor_options: Vec<&'static str>,
}

impl Vendors {
    pub fn new() -> Self {
        Vendors {
            prettified_vendor_options: Vec::from([
                "Agora",
                "Amazon Web Services",
                "Ansible",
                "Auth0",
                "Bitbucket",
                "Braintree",
                "Cloudflare",
                "Datadog",
                "DigitalOcean",
                "Discord",
                "Docker",
                "Dropbox",
                "Facebook",
                "Figma",
                "GitHub",
                "GitLab",
                "Google",
                "Google Cloud",
                "Google Gemini",
                "Jenkins",
                "Jira Software",
                "Kubernetes",
                "Linear",
                "LinkedIn",
                "Mailchimp",
                "Microsoft Azure",
                "Mixpanel",
                "Netlify",
                "OpenAI",
                "Other",
                "PayPal",
                "Pulumi",
                "Reddit",
                "Salesforce",
                "Segment",
                "SendGrid",
                "Shopify",
                "Slack",
                "Stripe",
                "Terraform",
                "Trello",
                "Twilio",
                "Vercel",
                "X",
                "Zoom",
            ]),
        }
    }

    pub fn vendor_normalize(vendor: &str) -> &'static str {
        match vendor {
            "Agora" => "agora",
            "Amazon Web Services" => "amazonwebservices",
            "Ansible" => "ansible",
            "Auth0" => "auth0",
            "Bitbucket" => "bitbucket",
            "Braintree" => "braintree",
            "Cloudflare" => "cloudflare",
            "Datadog" => "datadog",
            "DigitalOcean" => "digitalocean",
            "Discord" => "discord",
            "Docker" => "docker",
            "Dropbox" => "dropbox",
            "Facebook" => "facebook",
            "Figma" => "figma",
            "GitHub" => "github",
            "GitLab" => "gitlab",
            "Google" => "google",
            "Google Cloud" => "googlecloud",
            "Google Gemini" => "googlegemini",
            "Jenkins" => "jenkins",
            "Jira Software" => "jirasoftware",
            "Kubernetes" => "kubernetes",
            "Linear" => "linear",
            "LinkedIn" => "linkedin",
            "Mailchimp" => "mailchimp",
            "Microsoft Azure" => "microsoftazure",
            "Mixpanel" => "mixpanel",
            "Netlify" => "netlify",
            "OpenAI" => "openai",
            "Other" => "other",
            "PayPal" => "paypal",
            "Pulumi" => "pulumi",
            "Reddit" => "reddit",
            "Salesforce" => "salesforce",
            "Segment" => "segment",
            "SendGrid" => "sendgrid",
            "Shopify" => "shopify",
            "Slack" => "slack",
            "Stripe" => "stripe",
            "Terraform" => "terraform",
            "Trello" => "trello",
            "Twilio" => "twilio",
            "Vercel" => "vercel",
            "X" => "x",
            "Zoom" => "zoom",
            _ => {
                print_formatted_error("Service error. Please try again.");
                std::process::exit(1);
            }
        }
    }
}
